### ISSUE TITLE
Crash with NullPointerException

### ISSUE THREAD

**Issue by BohdanNoname** [Gkemon/Android-XML-to-PDF-Generator#53]
When user back to previous screen on this stage, get next RuntimeException 
![photo_2022-12-28_21-16-34](https://user-images.githubusercontent.com/52040225/209861696-58f372cf-f31a-4e07-b42f-f4172b417046.jpg)

E/AndroidRuntime: FATAL EXCEPTION: main
Process: package.name, PID: 12675
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1494040958, result=0, data=null} to activity {package.name/com.MainActivity}: java.lang.NullPointerException: uri
at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5379)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7842)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: uri
at java.util.Objects.requireNonNull(Objects.java:245)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)
at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1675)
at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1622)
at com.gkemon.XMLtoPDF.PdfGenerator$Builder.writePDFOnSavedBlankPDFFile(PdfGenerator.java:445)
at com.gkemon.XMLtoPDF.PdfGenerator$Builder.lambda$print$0$com-gkemon-XMLtoPDF-PdfGenerator$Builder(PdfGenerator.java:422)
at com.gkemon.XMLtoPDF.PdfGenerator$Builder$$ExternalSyntheticLambda1.onBlankPDFCreatedInSharedStorage(Unknown Source:4)
at com.gkemon.XMLtoPDF.PdfGenerator$XmlToPDFLifecycleObserver.lambda$onCreate$0$com-gkemon-XMLtoPDF-PdfGenerator$XmlToPDFLifecycleObserver(PdfGenerator.java:696)
at com.gkemon.XMLtoPDF.PdfGenerator$XmlToPDFLifecycleObserver$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:777)
at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:152)
at android.app.Activity.dispatchActivityResult(Activity.java:8385)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5333)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5379) 
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) 
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7842) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by Gkemon** [comment]
@BohdanNoname, can you please describe how to reproduce it on my device.
